### ISSUE TITLE
Small typo in test command example from the phase1 handout

### ISSUE THREAD

**Issue by adadima** [6035/fa19#1]
In the handout for phase1 it says to run the following command for testing the scanner on a single input file: `./run.sh --target=scan tests/scanner/input/char1`.

I think that the file extension might be missing, it only worked when I ran:
`./run.sh --target=scan tests/scanner/input/char1.dcf`. 

I figured to bring it up since if this is indeed a typo and not something wrong with my setup, then others might waste time on this too.

**Comment by jchoi5me** [comment]
You are right, I just made the fix.

Thank you for pointing this out!
